
# Final Project

## Description
R is the tool serving for analyzing data and visualizing results. In the final project, you will use the R programming skills you learn from this course and also the knowledge outside the course (other R techniques you are interested in and your professional knowledge in your study major) to solve a research question. The research question could be related your study field (e.g., public policy, urban and regional planning, public health, etc.), or what you are interested in, or your previous course or research project but you do it with R instead. You could use any packages in R to solve the problem. For example, you could use plots to do descriptive analysis. Or you could use regression to find correlation or causality. The final product is a poster.

This assignment accounts for 30% of your final grades.

## Timeline

To accomplish the final project, you need to finish two tasks.

|   | Task          | Descriptions                                             | Due Date |
|:-:|---------------|----------------------------------------------------------|----------|
| 1 | Proposal      | Your research question and data source introduction      | 16th Apr.|
| 2 | Poster        | A poster representing your analysis result               | 7th May. |


## Proposal of problem statement

In this task, you will need to submit the proposal file (either word or pdf). The instructor will give you feedback but will not grade this part. The rubric is just for helping you check the requirements. See the canvas for a template of the proposal.

| Requirements                                                                                                              |
|---------------------------------------------------------------------------------------------------------------------------|
| Research question and illustration of research question is clear                                                          |
| Clearly state the data sources (what is the dataset and where do you find it)                                             |
| State the potential method you will use for data analysis (descriptive analysis, simple regression, etc.)                 |

The proposal should be less than one page, 12 font size.

## Final submission

In this part, **you will submit your data file, revised codes (R file), and the poster (PDF file)**. The instructor will grade them based on the rubric below.

The poster  

* should include research question (as the title of the poster), your name, illustration of your research question, data source, plots/tables, and important findings
* should include at least two plots generated by your R codes
* should include no more than four plots
* could include include one table generated by your R codes, but not necessarily

| Category | Requirements                                                                                                                  | Grades |
|----------|-------------------------------------------------------------------------------------------------------------------------------|--------|
| Codes    | Codes could generate the results (figures, tables, and related statistics)                                                    | 7      |
|          | Necessary notes for the codes                                                                                                 | 2      |
|          | Codes is neat and well-organized                                                                                              | 1      |
| Poster   | Research question and study purpose are clear                                                                                 | 2      |
|          | Clearly state the data sources (what is the dataset, where do you find it, what variables you use from this dataset)          | 2      |
|          | Figures contain the necessary parts, well-organized, and visually good/ tables are well-organized                             | 12     |
|          | Description of the important findings is clear                                                                                | 2      |
|          | Poster is well-organized                                                                                                      | 2      |

You can find a poster template file (PowerPoint file) on Canvas website. You can choose to follow the format of this template or change it.


