--- 
title: "PA 5928 Data Management & Visualization with R (Spring 2021)"
author: "Tao Tao (University of Minnesota)"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: "This is the website for couse PA 5928 in the University of Minnesota"
---

# Course Syllabus

## Course description

Introduction to ``RStudio`` software. Use of ``RStudio`` to carry out ``R`` file and related dataset management functions. Tools and techniques for data analysis and statistical programming in quantitative research or related applied areas. Topics include data selection, data manipulation, and data visualization (including charts, plots, histograms, maps, and other graphs).

## Course prerequisites

Introductory statistics; ability to create bar graphs, line graphs, and scatter plots in MS Excel; and familiarity with principles of data visualization.

## Logistics

**Lecture section**: 2:30 - 3:45 pm Tuesday and Thursday  
**Instructor**: Tao Tao, taotao@umn.edu  
**Instruction mode**: Completely online (Link in Canvas)  
**Office hour**: 4:00-5:00 pm Tuesday (Link in Canvas) or by appointment  
**Canvas**: All course notes will be posted in this course website, but links will be updated on Canvas simultaneously. Canvas will also be used to submit your assignments, final project, and grades. Make sure you have enabled the notification of this course on Canvas.

## Course learning outcomes

At the end of this course, students will be able to:

1. Use RStudio to carry out R file and related database management
2. Use R to work with different types of databases and conduct basic data management
3. Use R to visualize data with different types of plots
4. Use R to carry out exploratory data analysis

## Readings
The online note is the main study material in this course.  The course has several supplementary reading materials, which are available on Canvas.  
1. Wickham, H. (2016). *ggplot2: elegant graphics for data analysis*. Springer.  
2. Wickham, H., & Grolemund, G. (2016). *R for data science: import, tidy, transform, visualize, and model data*. O'Reilly Media, Inc.


## Weekly assignment and final project

1. Weekly assignment includes in-class exercise and after-class assignment. Students are required to submit both of them (R codes) with necessary notes.
2. Weekly assignment is always due on next Monday 11:59 pm. *Missing deadline results in a penalty in grades (10% of the total grades for each 24 hours, less than 24 hours will be counted as 24 hours)*. Check your files before submission. *Wrong submission results in a penalty in grades (20% of the total grades)*.
3. Students will use the knowledge from this course to complete a final project (data analysis for a interested research question and make a poster to show off their work). You can find the description of the final project in the chapter of [final project](./final-project.html)).  
4. Grading policy

* Weekly assignment: 70%
* Final project: 30%

Weekly assignment grading rubric

| Requirements                                                                             | Grades |
|------------------------------------------------------------------------------------------|:------:|
| Codes could generate the results required by the problems                                | 6      |
| Necessary notes to indicate the general idea (usage, function, purpose, or mechanism)    | 3      |
| Codes and notes are neat and well-organized                                              | 1      |

## Course schedule (Tentative)

| Week       | Date   | Topic                                         |
|------------|--------|-----------------------------------------------|
| Week 1 Tue | Mar 9  | **Course introduction + Introduction to RStudio** |
| Week 1 Thu | Mar 11 | **Introduction to R**                             |
| Week 2 Tue | Mar 16 | **Data source introduction**                      |
| Week 2 Thu | Mar 18 | **Data manipulation with base functions**         |
| Week 3 Tue | Mar 23 | **Data manipulation with dplyr Part I**           |
| Week 3 Thu | Mar 25 | **Data manipulation with dplyr Part II**          |
| Week 4 Tue | Mar 30 | **Data visualization with base functions**        |
| Week 4 Thu | Apr 1  | **Data visualization with ggplot2 Part I**        |
| Week 5     |        | **Spring break**                                  |
| Week 6 Tue | Apr 13 | **Data visualization with ggplot2 Part II**       |
| Week 6 Thu | Apr 15 | **Data visualization with ggplot2 Part III**      |
| Week 7 Tue | Apr 20 | **Simple statistics in R Part I**                 |
| Week 7 Thu | Apr 22 | **Simple statistics in R Part II**                |
| Week 8 Tue | Apr 27 | **Exploratory Data Analysis Part I**              |
| Week 8 Thu | Apr 29 | **Exploratory Data Analysis Part II**             |

## Homework and projects collaboration and submission policy

1. **Students can discuss their works with other students, but must code and write up notes by themselves. [Plagiarism](https://communitystandards.umn.edu/content/plagiarism) is not allowed by the university policies. Please do be careful about this.**
2. Weekly assignments and projects should be submitted through Canvas.
3. If you cannot attend the class, please write an email to the instructor including a valid reason before the class.
4. When you communicate the instructor with emails, please include ``PA 5928`` at the beginning of your title.
