<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 8 Statistics in R | PA 5928 Data Management &amp; Visualization with R (Spring 2021)</title>
  <meta name="description" content="This is the website for couse PA 5928 in the University of Minnesota" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 8 Statistics in R | PA 5928 Data Management &amp; Visualization with R (Spring 2021)" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the website for couse PA 5928 in the University of Minnesota" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 8 Statistics in R | PA 5928 Data Management &amp; Visualization with R (Spring 2021)" />
  
  <meta name="twitter:description" content="This is the website for couse PA 5928 in the University of Minnesota" />
  

<meta name="author" content="Tao Tao (University of Minnesota)" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-visualization-with-ggplot2.html"/>
<link rel="next" href="exploratory-data-analysis.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">PA 5928 R course</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Course Syllabus</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#course-description"><i class="fa fa-check"></i><b>1.1</b> Course description</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#course-prerequisites"><i class="fa fa-check"></i><b>1.2</b> Course prerequisites</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#logistics"><i class="fa fa-check"></i><b>1.3</b> Logistics</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#course-learning-outcomes"><i class="fa fa-check"></i><b>1.4</b> Course learning outcomes</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#readings"><i class="fa fa-check"></i><b>1.5</b> Readings</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#weekly-assignment-and-final-project"><i class="fa fa-check"></i><b>1.6</b> Weekly assignment and final project</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#course-schedule-tentative"><i class="fa fa-check"></i><b>1.7</b> Course schedule (Tentative)</a></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#homework-and-projects-collaboration-and-submission-policy"><i class="fa fa-check"></i><b>1.8</b> Homework and projects collaboration and submission policy</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction-to-rstudio.html"><a href="introduction-to-rstudio.html"><i class="fa fa-check"></i><b>2</b> Introduction to RStudio</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introduction-to-rstudio.html"><a href="introduction-to-rstudio.html#what-is-r"><i class="fa fa-check"></i><b>2.1</b> What is R</a></li>
<li class="chapter" data-level="2.2" data-path="introduction-to-rstudio.html"><a href="introduction-to-rstudio.html#what-is-rstudio"><i class="fa fa-check"></i><b>2.2</b> What is RStudio</a></li>
<li class="chapter" data-level="2.3" data-path="introduction-to-rstudio.html"><a href="introduction-to-rstudio.html#install-r-rstudio"><i class="fa fa-check"></i><b>2.3</b> Install R + RStudio</a></li>
<li class="chapter" data-level="2.4" data-path="introduction-to-rstudio.html"><a href="introduction-to-rstudio.html#familiar-with-the-user-interface-of-rstudio"><i class="fa fa-check"></i><b>2.4</b> Familiar with the user interface of RStudio</a></li>
<li class="chapter" data-level="2.5" data-path="introduction-to-rstudio.html"><a href="introduction-to-rstudio.html#create-and-save-r-file"><i class="fa fa-check"></i><b>2.5</b> Create and save R file</a></li>
<li class="chapter" data-level="2.6" data-path="introduction-to-rstudio.html"><a href="introduction-to-rstudio.html#print-hello-world"><i class="fa fa-check"></i><b>2.6</b> Print Hello, world</a></li>
<li class="chapter" data-level="2.7" data-path="introduction-to-rstudio.html"><a href="introduction-to-rstudio.html#install-and-use-r-packages"><i class="fa fa-check"></i><b>2.7</b> Install and use R Packages</a></li>
<li class="chapter" data-level="2.8" data-path="introduction-to-rstudio.html"><a href="introduction-to-rstudio.html#make-notes"><i class="fa fa-check"></i><b>2.8</b> Make notes</a></li>
<li class="chapter" data-level="2.9" data-path="introduction-to-rstudio.html"><a href="introduction-to-rstudio.html#tips"><i class="fa fa-check"></i><b>2.9</b> Tips</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>3</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#why-r-and-why-not-r"><i class="fa fa-check"></i><b>3.1</b> Why R and why not R?</a></li>
<li class="chapter" data-level="3.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#variable-name"><i class="fa fa-check"></i><b>3.2</b> Variable name</a></li>
<li class="chapter" data-level="3.3" data-path="introduction-to-r.html"><a href="introduction-to-r.html#variable-types"><i class="fa fa-check"></i><b>3.3</b> Variable types</a></li>
<li class="chapter" data-level="3.4" data-path="introduction-to-r.html"><a href="introduction-to-r.html#operations"><i class="fa fa-check"></i><b>3.4</b> Operations</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#assignment-operations"><i class="fa fa-check"></i><b>3.4.1</b> Assignment operations</a></li>
<li class="chapter" data-level="3.4.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#arithmetic-operations"><i class="fa fa-check"></i><b>3.4.2</b> Arithmetic operations</a></li>
<li class="chapter" data-level="3.4.3" data-path="introduction-to-r.html"><a href="introduction-to-r.html#relational-operations"><i class="fa fa-check"></i><b>3.4.3</b> Relational operations</a></li>
<li class="chapter" data-level="3.4.4" data-path="introduction-to-r.html"><a href="introduction-to-r.html#logical-operations"><i class="fa fa-check"></i><b>3.4.4</b> Logical operations</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="introduction-to-r.html"><a href="introduction-to-r.html#data-structures"><i class="fa fa-check"></i><b>3.5</b> Data structures</a></li>
<li class="chapter" data-level="3.6" data-path="introduction-to-r.html"><a href="introduction-to-r.html#conditional-statement-if"><i class="fa fa-check"></i><b>3.6</b> Conditional statement (if)</a></li>
<li class="chapter" data-level="3.7" data-path="introduction-to-r.html"><a href="introduction-to-r.html#loops"><i class="fa fa-check"></i><b>3.7</b> Loops</a></li>
<li class="chapter" data-level="3.8" data-path="introduction-to-r.html"><a href="introduction-to-r.html#functions"><i class="fa fa-check"></i><b>3.8</b> Functions</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-manipulation-with-base-functions.html"><a href="data-manipulation-with-base-functions.html"><i class="fa fa-check"></i><b>4</b> Data Manipulation with Base Functions</a>
<ul>
<li class="chapter" data-level="4.1" data-path="data-manipulation-with-base-functions.html"><a href="data-manipulation-with-base-functions.html#import-and-save-datasets"><i class="fa fa-check"></i><b>4.1</b> Import and save datasets</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="data-manipulation-with-base-functions.html"><a href="data-manipulation-with-base-functions.html#import-data-from-commonly-used-file-types"><i class="fa fa-check"></i><b>4.1.1</b> Import data from commonly-used file types</a></li>
<li class="chapter" data-level="4.1.2" data-path="data-manipulation-with-base-functions.html"><a href="data-manipulation-with-base-functions.html#save-file"><i class="fa fa-check"></i><b>4.1.2</b> Save file</a></li>
<li class="chapter" data-level="4.1.3" data-path="data-manipulation-with-base-functions.html"><a href="data-manipulation-with-base-functions.html#file-location"><i class="fa fa-check"></i><b>4.1.3</b> File location</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="data-manipulation-with-base-functions.html"><a href="data-manipulation-with-base-functions.html#view-data"><i class="fa fa-check"></i><b>4.2</b> View data</a></li>
<li class="chapter" data-level="4.3" data-path="data-manipulation-with-base-functions.html"><a href="data-manipulation-with-base-functions.html#data-selection"><i class="fa fa-check"></i><b>4.3</b> Data selection</a></li>
<li class="chapter" data-level="4.4" data-path="data-manipulation-with-base-functions.html"><a href="data-manipulation-with-base-functions.html#conditional-selection"><i class="fa fa-check"></i><b>4.4</b> Conditional selection</a></li>
<li class="chapter" data-level="4.5" data-path="data-manipulation-with-base-functions.html"><a href="data-manipulation-with-base-functions.html#deal-with-missing-values"><i class="fa fa-check"></i><b>4.5</b> Deal with missing values</a></li>
<li class="chapter" data-level="4.6" data-path="data-manipulation-with-base-functions.html"><a href="data-manipulation-with-base-functions.html#subset"><i class="fa fa-check"></i><b>4.6</b> Subset</a></li>
<li class="chapter" data-level="4.7" data-path="data-manipulation-with-base-functions.html"><a href="data-manipulation-with-base-functions.html#merge-two-datasets"><i class="fa fa-check"></i><b>4.7</b> Merge two datasets</a></li>
<li class="chapter" data-level="4.8" data-path="data-manipulation-with-base-functions.html"><a href="data-manipulation-with-base-functions.html#column-operation"><i class="fa fa-check"></i><b>4.8</b> Column operation</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-manipulation-with-dplyr.html"><a href="data-manipulation-with-dplyr.html"><i class="fa fa-check"></i><b>5</b> Data Manipulation with dplyr</a>
<ul>
<li class="chapter" data-level="5.1" data-path="data-manipulation-with-dplyr.html"><a href="data-manipulation-with-dplyr.html#select"><i class="fa fa-check"></i><b>5.1</b> select()</a></li>
<li class="chapter" data-level="5.2" data-path="data-manipulation-with-dplyr.html"><a href="data-manipulation-with-dplyr.html#filter"><i class="fa fa-check"></i><b>5.2</b> filter()</a></li>
<li class="chapter" data-level="5.3" data-path="data-manipulation-with-dplyr.html"><a href="data-manipulation-with-dplyr.html#arrange"><i class="fa fa-check"></i><b>5.3</b> arrange()</a></li>
<li class="chapter" data-level="5.4" data-path="data-manipulation-with-dplyr.html"><a href="data-manipulation-with-dplyr.html#mutate"><i class="fa fa-check"></i><b>5.4</b> mutate()</a></li>
<li class="chapter" data-level="5.5" data-path="data-manipulation-with-dplyr.html"><a href="data-manipulation-with-dplyr.html#group_by-and-summarise"><i class="fa fa-check"></i><b>5.5</b> group_by() and summarise()</a></li>
<li class="chapter" data-level="5.6" data-path="data-manipulation-with-dplyr.html"><a href="data-manipulation-with-dplyr.html#join"><i class="fa fa-check"></i><b>5.6</b> join()</a></li>
<li class="chapter" data-level="5.7" data-path="data-manipulation-with-dplyr.html"><a href="data-manipulation-with-dplyr.html#pivot_wider-and-pivot_longer-in-tidyr"><i class="fa fa-check"></i><b>5.7</b> pivot_wider() and pivot_longer() in tidyr</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="data-visualization-with-base-functions.html"><a href="data-visualization-with-base-functions.html"><i class="fa fa-check"></i><b>6</b> Data Visualization with Base Functions</a>
<ul>
<li class="chapter" data-level="6.1" data-path="data-visualization-with-base-functions.html"><a href="data-visualization-with-base-functions.html#scatter-plot"><i class="fa fa-check"></i><b>6.1</b> Scatter plot</a></li>
<li class="chapter" data-level="6.2" data-path="data-visualization-with-base-functions.html"><a href="data-visualization-with-base-functions.html#line-plot"><i class="fa fa-check"></i><b>6.2</b> Line plot</a></li>
<li class="chapter" data-level="6.3" data-path="data-visualization-with-base-functions.html"><a href="data-visualization-with-base-functions.html#bar-plot"><i class="fa fa-check"></i><b>6.3</b> Bar plot</a></li>
<li class="chapter" data-level="6.4" data-path="data-visualization-with-base-functions.html"><a href="data-visualization-with-base-functions.html#add-more-elements-in-the-plots"><i class="fa fa-check"></i><b>6.4</b> Add more elements in the plots</a></li>
<li class="chapter" data-level="6.5" data-path="data-visualization-with-base-functions.html"><a href="data-visualization-with-base-functions.html#pie-chart"><i class="fa fa-check"></i><b>6.5</b> Pie chart</a></li>
<li class="chapter" data-level="6.6" data-path="data-visualization-with-base-functions.html"><a href="data-visualization-with-base-functions.html#boxplot"><i class="fa fa-check"></i><b>6.6</b> Boxplot</a></li>
<li class="chapter" data-level="6.7" data-path="data-visualization-with-base-functions.html"><a href="data-visualization-with-base-functions.html#color-in-r"><i class="fa fa-check"></i><b>6.7</b> Color in R</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html"><i class="fa fa-check"></i><b>7</b> Data Visualization with ggplot2</a>
<ul>
<li class="chapter" data-level="7.1" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#grammer-of-graphics-gg"><i class="fa fa-check"></i><b>7.1</b> Grammer of Graphics (gg)</a></li>
<li class="chapter" data-level="7.2" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#data-aesthetics-and-geometries"><i class="fa fa-check"></i><b>7.2</b> Data, Aesthetics, and Geometries</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#scatter-plot-1"><i class="fa fa-check"></i><b>7.2.1</b> Scatter plot</a></li>
<li class="chapter" data-level="7.2.2" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#bar-plot-1"><i class="fa fa-check"></i><b>7.2.2</b> Bar plot</a></li>
<li class="chapter" data-level="7.2.3" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#line-plot-1"><i class="fa fa-check"></i><b>7.2.3</b> Line plot</a></li>
<li class="chapter" data-level="7.2.4" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#boxplot-1"><i class="fa fa-check"></i><b>7.2.4</b> Boxplot</a></li>
<li class="chapter" data-level="7.2.5" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#pie-chart-1"><i class="fa fa-check"></i><b>7.2.5</b> Pie chart</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#facets"><i class="fa fa-check"></i><b>7.3</b> Facets</a></li>
<li class="chapter" data-level="7.4" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#coordinates"><i class="fa fa-check"></i><b>7.4</b> Coordinates</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#zooming-in-and-out"><i class="fa fa-check"></i><b>7.4.1</b> Zooming in and out</a></li>
<li class="chapter" data-level="7.4.2" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#ratio"><i class="fa fa-check"></i><b>7.4.2</b> Ratio</a></li>
<li class="chapter" data-level="7.4.3" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#swaping-the-axes"><i class="fa fa-check"></i><b>7.4.3</b> Swaping the axes</a></li>
<li class="chapter" data-level="7.4.4" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#polar-coordinate-system"><i class="fa fa-check"></i><b>7.4.4</b> Polar coordinate system</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#themes"><i class="fa fa-check"></i><b>7.5</b> Themes</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#add-labels"><i class="fa fa-check"></i><b>7.5.1</b> Add labels</a></li>
<li class="chapter" data-level="7.5.2" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#change-ticks"><i class="fa fa-check"></i><b>7.5.2</b> Change ticks</a></li>
<li class="chapter" data-level="7.5.3" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#theme-function"><i class="fa fa-check"></i><b>7.5.3</b> theme() function</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="data-visualization-with-ggplot2.html"><a href="data-visualization-with-ggplot2.html#save-plot"><i class="fa fa-check"></i><b>7.6</b> Save plot</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="statistics-in-r.html"><a href="statistics-in-r.html"><i class="fa fa-check"></i><b>8</b> Statistics in R</a>
<ul>
<li class="chapter" data-level="8.1" data-path="statistics-in-r.html"><a href="statistics-in-r.html#plotting-statistics"><i class="fa fa-check"></i><b>8.1</b> Plotting statistics</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="statistics-in-r.html"><a href="statistics-in-r.html#fitting-the-general-trend-of-points"><i class="fa fa-check"></i><b>8.1.1</b> Fitting the general trend of points</a></li>
<li class="chapter" data-level="8.1.2" data-path="statistics-in-r.html"><a href="statistics-in-r.html#plotting-distribution"><i class="fa fa-check"></i><b>8.1.2</b> Plotting distribution</a></li>
<li class="chapter" data-level="8.1.3" data-path="statistics-in-r.html"><a href="statistics-in-r.html#density-plot-of-distribution"><i class="fa fa-check"></i><b>8.1.3</b> Density plot of distribution</a></li>
<li class="chapter" data-level="8.1.4" data-path="statistics-in-r.html"><a href="statistics-in-r.html#box-plot-of-distribution"><i class="fa fa-check"></i><b>8.1.4</b> Box plot of distribution</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="statistics-in-r.html"><a href="statistics-in-r.html#anotation-of-statistics"><i class="fa fa-check"></i><b>8.2</b> Anotation of statistics</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="statistics-in-r.html"><a href="statistics-in-r.html#bar-plot-2"><i class="fa fa-check"></i><b>8.2.1</b> bar plot</a></li>
<li class="chapter" data-level="8.2.2" data-path="statistics-in-r.html"><a href="statistics-in-r.html#line-plot-2"><i class="fa fa-check"></i><b>8.2.2</b> line plot</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="statistics-in-r.html"><a href="statistics-in-r.html#simple-statistics"><i class="fa fa-check"></i><b>8.3</b> Simple statistics</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="statistics-in-r.html"><a href="statistics-in-r.html#mean-and-median"><i class="fa fa-check"></i><b>8.3.1</b> Mean and median</a></li>
<li class="chapter" data-level="8.3.2" data-path="statistics-in-r.html"><a href="statistics-in-r.html#minimum-and-maximum-value"><i class="fa fa-check"></i><b>8.3.2</b> Minimum and maximum value</a></li>
<li class="chapter" data-level="8.3.3" data-path="statistics-in-r.html"><a href="statistics-in-r.html#quartile"><i class="fa fa-check"></i><b>8.3.3</b> Quartile</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="statistics-in-r.html"><a href="statistics-in-r.html#linear-regression"><i class="fa fa-check"></i><b>8.4</b> Linear regression</a></li>
<li class="chapter" data-level="8.5" data-path="statistics-in-r.html"><a href="statistics-in-r.html#logistic-regression"><i class="fa fa-check"></i><b>8.5</b> Logistic regression</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html"><i class="fa fa-check"></i><b>9</b> Exploratory Data Analysis</a>
<ul>
<li class="chapter" data-level="9.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#case-1-race-and-personal-income-in-the-city-of-minneapolis-2010-2019"><i class="fa fa-check"></i><b>9.1</b> Case 1: Race and personal income in the city of Minneapolis (2010-2019)</a></li>
<li class="chapter" data-level="9.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#case-2-race-and-employment-rate-in-the-city-of-minneapolis-2010-2019"><i class="fa fa-check"></i><b>9.2</b> Case 2: Race and employment rate in the city of Minneapolis (2010-2019)</a></li>
<li class="chapter" data-level="9.3" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#case-3-population-density-and-election-result-in-the-us-2020"><i class="fa fa-check"></i><b>9.3</b> Case 3: Population density and election result in the US (2020)</a></li>
<li class="chapter" data-level="9.4" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#case-4-factors-that-influence-students-performance"><i class="fa fa-check"></i><b>9.4</b> Case 4: Factors that influence students’ performance</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="final-project.html"><a href="final-project.html"><i class="fa fa-check"></i><b>10</b> Final Project</a>
<ul>
<li class="chapter" data-level="10.1" data-path="final-project.html"><a href="final-project.html#description"><i class="fa fa-check"></i><b>10.1</b> Description</a></li>
<li class="chapter" data-level="10.2" data-path="final-project.html"><a href="final-project.html#timeline"><i class="fa fa-check"></i><b>10.2</b> Timeline</a></li>
<li class="chapter" data-level="10.3" data-path="final-project.html"><a href="final-project.html#proposal-of-problem-statement"><i class="fa fa-check"></i><b>10.3</b> Proposal of problem statement</a></li>
<li class="chapter" data-level="10.4" data-path="final-project.html"><a href="final-project.html#potential-data-sources"><i class="fa fa-check"></i><b>10.4</b> Potential data sources</a></li>
<li class="chapter" data-level="10.5" data-path="final-project.html"><a href="final-project.html#final-submission"><i class="fa fa-check"></i><b>10.5</b> Final submission</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>11</b> References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">PA 5928 Data Management &amp; Visualization with R (Spring 2021)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="statistics-in-r" class="section level1" number="8">
<h1><span class="header-section-number">Chapter 8</span> Statistics in R</h1>
<p>In this chapter, we are going to use R to firstly drawing the statistics in the plots and carry out statistical analysis.</p>
<div class="sourceCode" id="cb412"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb412-1"><a href="statistics-in-r.html#cb412-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb412-2"><a href="statistics-in-r.html#cb412-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb412-3"><a href="statistics-in-r.html#cb412-3" aria-hidden="true" tabindex="-1"></a>minneaplis <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&#39;minneapolis.csv&#39;</span>)</span></code></pre></div>
<div id="plotting-statistics" class="section level2" number="8.1">
<h2><span class="header-section-number">8.1</span> Plotting statistics</h2>
<div id="fitting-the-general-trend-of-points" class="section level3" number="8.1.1">
<h3><span class="header-section-number">8.1.1</span> Fitting the general trend of points</h3>
<p>You could fit a line to see the general trend of the scatter plot by adding <code>stat_smooth()</code>.</p>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb413-1"><a href="statistics-in-r.html#cb413-1" aria-hidden="true" tabindex="-1"></a><span class="do">## select observations from 2017</span></span>
<span id="cb413-2"><a href="statistics-in-r.html#cb413-2" aria-hidden="true" tabindex="-1"></a>minneapolis_2017 <span class="ot">&lt;-</span> <span class="fu">filter</span>(minneaplis, YEAR <span class="sc">==</span> <span class="dv">2017</span>)</span>
<span id="cb413-3"><a href="statistics-in-r.html#cb413-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb413-4"><a href="statistics-in-r.html#cb413-4" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(minneapolis_2017, <span class="fu">aes</span>(AGE, INCTOT)) <span class="sc">+</span></span>
<span id="cb413-5"><a href="statistics-in-r.html#cb413-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() </span>
<span id="cb413-6"><a href="statistics-in-r.html#cb413-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb413-7"><a href="statistics-in-r.html#cb413-7" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">&#39;lm&#39;</span>) <span class="co"># fit a linear line for the points</span></span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 454 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 454 rows containing missing values (geom_point).</code></pre>
<p><img src="PA_5928_2021_spring_files/figure-html/unnamed-chunk-208-1.png" width="672" /></p>
<div class="sourceCode" id="cb417"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb417-1"><a href="statistics-in-r.html#cb417-1" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">&#39;loess&#39;</span>) <span class="co"># non-linear line</span></span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 454 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 454 rows containing missing values (geom_point).</code></pre>
<p><img src="PA_5928_2021_spring_files/figure-html/unnamed-chunk-209-1.png" width="672" /></p>
<p>It seems that the non-linear relationship makes more sense.</p>
</div>
<div id="plotting-distribution" class="section level3" number="8.1.2">
<h3><span class="header-section-number">8.1.2</span> Plotting distribution</h3>
<p>You could draw a histogram for the dataset with <code>geom_histogram()</code>.</p>
<div class="sourceCode" id="cb421"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb421-1"><a href="statistics-in-r.html#cb421-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(minneapolis_2017, <span class="fu">aes</span>(AGE))</span>
<span id="cb421-2"><a href="statistics-in-r.html#cb421-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb421-3"><a href="statistics-in-r.html#cb421-3" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>) <span class="co"># the width of each category is 5</span></span></code></pre></div>
<p><img src="PA_5928_2021_spring_files/figure-html/unnamed-chunk-210-1.png" width="672" /></p>
<div class="sourceCode" id="cb422"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb422-1"><a href="statistics-in-r.html#cb422-1" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>) <span class="co"># the number of bins is 30</span></span></code></pre></div>
<p><img src="PA_5928_2021_spring_files/figure-html/unnamed-chunk-211-1.png" width="672" /></p>
<p>You could fit a density line for the histogram.</p>
<div class="sourceCode" id="cb423"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb423-1"><a href="statistics-in-r.html#cb423-1" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="fu">aes</span>( <span class="at">y =</span> ..density..), <span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">col =</span> <span class="st">&#39;Black&#39;</span>, <span class="at">fill =</span> <span class="st">&#39;White&#39;</span>) <span class="sc">+</span> <span class="co"># use density instead of count</span></span>
<span id="cb423-2"><a href="statistics-in-r.html#cb423-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> .<span class="dv">2</span>, <span class="at">fill =</span> <span class="st">&#39;Grey&#39;</span>) </span></code></pre></div>
<p><img src="PA_5928_2021_spring_files/figure-html/unnamed-chunk-212-1.png" width="672" /></p>
</div>
<div id="density-plot-of-distribution" class="section level3" number="8.1.3">
<h3><span class="header-section-number">8.1.3</span> Density plot of distribution</h3>
<p><code>geom_freqpoly()</code> can serve a same purpose.</p>
<div class="sourceCode" id="cb424"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb424-1"><a href="statistics-in-r.html#cb424-1" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">geom_freqpoly</span>()</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="PA_5928_2021_spring_files/figure-html/unnamed-chunk-213-1.png" width="672" /></p>
</div>
<div id="box-plot-of-distribution" class="section level3" number="8.1.4">
<h3><span class="header-section-number">8.1.4</span> Box plot of distribution</h3>
<p>Another way to show more statistics about your data is box plot, which we have been introduced before.</p>
<div class="sourceCode" id="cb426"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb426-1"><a href="statistics-in-r.html#cb426-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(minneapolis_2017, <span class="fu">aes</span>(<span class="fu">factor</span>(SEX), INCTOT))</span>
<span id="cb426-2"><a href="statistics-in-r.html#cb426-2" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 454 rows containing non-finite values (stat_boxplot).</code></pre>
<p><img src="PA_5928_2021_spring_files/figure-html/unnamed-chunk-214-1.png" width="672" /></p>
</div>
</div>
<div id="anotation-of-statistics" class="section level2" number="8.2">
<h2><span class="header-section-number">8.2</span> Anotation of statistics</h2>
<p>We can use <code>geom_text()</code> to annotate the statistics in the plot.</p>
<div id="bar-plot-2" class="section level3" number="8.2.1">
<h3><span class="header-section-number">8.2.1</span> bar plot</h3>
<div class="sourceCode" id="cb428"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb428-1"><a href="statistics-in-r.html#cb428-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(minneapolis_2017, <span class="fu">aes</span>(<span class="at">x =</span> RACE)) <span class="sc">+</span></span>
<span id="cb428-2"><a href="statistics-in-r.html#cb428-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb428-3"><a href="statistics-in-r.html#cb428-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> ..count..), <span class="at">stat =</span> <span class="st">&quot;count&quot;</span>, <span class="at">vjust =</span> <span class="fl">1.5</span>, <span class="at">colour =</span> <span class="st">&quot;white&quot;</span>)</span></code></pre></div>
<p><img src="PA_5928_2021_spring_files/figure-html/unnamed-chunk-215-1.png" width="672" /></p>
<div class="sourceCode" id="cb429"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb429-1"><a href="statistics-in-r.html#cb429-1" aria-hidden="true" tabindex="-1"></a><span class="do">## count the number of respondents based on RACE</span></span>
<span id="cb429-2"><a href="statistics-in-r.html#cb429-2" aria-hidden="true" tabindex="-1"></a>minneaplis_race <span class="ot">&lt;-</span> minneapolis_2017 <span class="sc">%&gt;%</span> </span>
<span id="cb429-3"><a href="statistics-in-r.html#cb429-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(RACE) <span class="sc">%&gt;%</span> </span>
<span id="cb429-4"><a href="statistics-in-r.html#cb429-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb429-5"><a href="statistics-in-r.html#cb429-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb429-6"><a href="statistics-in-r.html#cb429-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(minneaplis_race, <span class="fu">aes</span>(RACE, count)) <span class="sc">+</span></span>
<span id="cb429-7"><a href="statistics-in-r.html#cb429-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb429-8"><a href="statistics-in-r.html#cb429-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.3</span>)</span></code></pre></div>
<p><img src="PA_5928_2021_spring_files/figure-html/unnamed-chunk-216-1.png" width="672" /></p>
</div>
<div id="line-plot-2" class="section level3" number="8.2.2">
<h3><span class="header-section-number">8.2.2</span> line plot</h3>
<div class="sourceCode" id="cb430"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb430-1"><a href="statistics-in-r.html#cb430-1" aria-hidden="true" tabindex="-1"></a><span class="do">## calculate the average personal income for each year</span></span>
<span id="cb430-2"><a href="statistics-in-r.html#cb430-2" aria-hidden="true" tabindex="-1"></a>minneapolis_year <span class="ot">&lt;-</span> minneapolis <span class="sc">%&gt;%</span> </span>
<span id="cb430-3"><a href="statistics-in-r.html#cb430-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR) <span class="sc">%&gt;%</span> </span>
<span id="cb430-4"><a href="statistics-in-r.html#cb430-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">AvgInc =</span> <span class="fu">mean</span>(INCTOT, <span class="at">na.rm =</span> T))</span>
<span id="cb430-5"><a href="statistics-in-r.html#cb430-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb430-6"><a href="statistics-in-r.html#cb430-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(minneapolis_year, <span class="fu">aes</span>(YEAR, AvgInc)) <span class="sc">+</span></span>
<span id="cb430-7"><a href="statistics-in-r.html#cb430-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">col =</span> <span class="st">&#39;Blue&#39;</span>) <span class="sc">+</span></span>
<span id="cb430-8"><a href="statistics-in-r.html#cb430-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(AvgInc)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb430-9"><a href="statistics-in-r.html#cb430-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">2010</span><span class="sc">:</span><span class="dv">2019</span>))</span></code></pre></div>
<p><img src="PA_5928_2021_spring_files/figure-html/unnamed-chunk-217-1.png" width="672" /></p>
<div class="sourceCode" id="cb431"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb431-1"><a href="statistics-in-r.html#cb431-1" aria-hidden="true" tabindex="-1"></a><span class="do">## calculate the average personal income for each racial group in each year</span></span>
<span id="cb431-2"><a href="statistics-in-r.html#cb431-2" aria-hidden="true" tabindex="-1"></a>minneapolis_year_race <span class="ot">&lt;-</span> minneapolis <span class="sc">%&gt;%</span> </span>
<span id="cb431-3"><a href="statistics-in-r.html#cb431-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(YEAR, RACE) <span class="sc">%&gt;%</span> </span>
<span id="cb431-4"><a href="statistics-in-r.html#cb431-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">AvgInc =</span> <span class="fu">mean</span>(INCTOT, <span class="at">na.rm =</span> T))</span>
<span id="cb431-5"><a href="statistics-in-r.html#cb431-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-6"><a href="statistics-in-r.html#cb431-6" aria-hidden="true" tabindex="-1"></a><span class="do">## line plot of the trend of average personal income</span></span>
<span id="cb431-7"><a href="statistics-in-r.html#cb431-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(minneapolis_year_race, <span class="fu">aes</span>(YEAR, AvgInc, <span class="at">col =</span> <span class="fu">factor</span>(RACE))) <span class="sc">+</span></span>
<span id="cb431-8"><a href="statistics-in-r.html#cb431-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb431-9"><a href="statistics-in-r.html#cb431-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(AvgInc)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.4</span>, <span class="at">color =</span> <span class="st">&#39;black&#39;</span>) <span class="sc">+</span></span>
<span id="cb431-10"><a href="statistics-in-r.html#cb431-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">2010</span><span class="sc">:</span><span class="dv">2019</span>))</span></code></pre></div>
<p><img src="PA_5928_2021_spring_files/figure-html/unnamed-chunk-218-1.png" width="672" /></p>
</div>
</div>
<div id="simple-statistics" class="section level2" number="8.3">
<h2><span class="header-section-number">8.3</span> Simple statistics</h2>
<p>We have touched some of the functions in this topic. For example, we could use <code>mean()</code> to compute the average value of a set of numbers.</p>
<div id="mean-and-median" class="section level3" number="8.3.1">
<h3><span class="header-section-number">8.3.1</span> Mean and median</h3>
<p>We could use the base functions to do some simple statistical analysis directly.</p>
<div class="sourceCode" id="cb432"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb432-1"><a href="statistics-in-r.html#cb432-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(minneapolis_2017<span class="sc">$</span>AGE) <span class="co"># mean</span></span></code></pre></div>
<pre><code>## [1] 36.0889</code></pre>
<div class="sourceCode" id="cb434"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb434-1"><a href="statistics-in-r.html#cb434-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(minneapolis_2017<span class="sc">$</span>AGE) <span class="co"># median</span></span></code></pre></div>
<pre><code>## [1] 32</code></pre>
</div>
<div id="minimum-and-maximum-value" class="section level3" number="8.3.2">
<h3><span class="header-section-number">8.3.2</span> Minimum and maximum value</h3>
<div class="sourceCode" id="cb436"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb436-1"><a href="statistics-in-r.html#cb436-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(minneapolis_2017<span class="sc">$</span>AGE) <span class="co"># minimum value</span></span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb438"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb438-1"><a href="statistics-in-r.html#cb438-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(minneapolis_2017<span class="sc">$</span>AGE) <span class="co"># maximum value</span></span></code></pre></div>
<pre><code>## [1] 95</code></pre>
</div>
<div id="quartile" class="section level3" number="8.3.3">
<h3><span class="header-section-number">8.3.3</span> Quartile</h3>
<div class="sourceCode" id="cb440"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb440-1"><a href="statistics-in-r.html#cb440-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">quantile</span>(minneapolis_2017<span class="sc">$</span>AGE)</span>
<span id="cb440-2"><a href="statistics-in-r.html#cb440-2" aria-hidden="true" tabindex="-1"></a>x <span class="co"># list of quartiles</span></span></code></pre></div>
<pre><code>##   0%  25%  50%  75% 100% 
##    0   20   32   52   95</code></pre>
<div class="sourceCode" id="cb442"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb442-1"><a href="statistics-in-r.html#cb442-1" aria-hidden="true" tabindex="-1"></a>x[<span class="dv">2</span>] <span class="co"># select the value by its index</span></span></code></pre></div>
<pre><code>## 25% 
##  20</code></pre>
<p>You could add value from 0 to 1 in the <code>quantile()</code> to find a specific value, for example, 40%.</p>
<div class="sourceCode" id="cb444"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb444-1"><a href="statistics-in-r.html#cb444-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(minneapolis_2017<span class="sc">$</span>AGE, <span class="fl">0.4</span>) <span class="co"># 40% of the dataset</span></span></code></pre></div>
<pre><code>## 40% 
##  28</code></pre>
</div>
</div>
<div id="linear-regression" class="section level2" number="8.4">
<h2><span class="header-section-number">8.4</span> Linear regression</h2>
<p>Before we start, let’s review some related knowledge first.</p>
<p>Regression is used to examine the linear relationships between the dependent variable and independent variables, where dependent variable is the one to be explained and independent variables (also called regressors, predictors, explanatory variables) are those may have influences on the dependent variable. For example, the dependent variable is personal income, and the independent variables are education, gender, age, <em>etc</em>. Among those independent variables, there are two types, one is continuous variable and the other is dummy variable. Continuous variable is variable with continuous values, such as income and age. Dummy variable is variable with values of 0 and 1. For example, gender, and people could use 1 for male, and 0 for female.</p>
<p>Suppose we have a dependent variable <span class="math inline">\(Y\)</span>, and two independent variables <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>, the regression model in assumption could be expressed as below,</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1X_1 + \beta_2X_2 + \epsilon\]</span>.</p>
<p>Where, <span class="math inline">\(\beta_0\)</span> is the intercept, <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span> are coefficients for <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>, <span class="math inline">\(\epsilon\)</span> is the error term which is the part of the dependent variable which cannot be explained by the intercept and independent variables. The target of regression is to estimate the value of <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, and <span class="math inline">\(\beta_2\)</span>, and test their significance. The coefficients for the independent variables stand for that if the independent variable change one unit, the dependent variable will change the amount of the coefficients.</p>
<p>The estimated model could be expressed as,</p>
<p><span class="math display">\[\hat{Y} = \hat{\beta_0} + \hat{\beta_1}X_1 + \hat{\beta_2}X_2\]</span></p>
<p>Those variables with hat are estimated variables.</p>
<p>While regression provides the estimated values of intercepts and coefficients, it also provides the significance of these estimates with p-values. When p-value is smaller, the estimates tend to be more significant. In R, the function will use some marks to indicate the significance levels. The significance level is the probability that the estimates are ‘true.’</p>
<table>
<thead>
<tr class="header">
<th>Mark</th>
<th>Descriptions of significance level</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>.</td>
<td>90%</td>
</tr>
<tr class="even">
<td>*</td>
<td>95%</td>
</tr>
<tr class="odd">
<td>**</td>
<td>99%</td>
</tr>
<tr class="even">
<td>***</td>
<td>99.9%</td>
</tr>
</tbody>
</table>
<p>To quantify the fitness of the model, we use <span class="math inline">\(R^2\)</span> with value from 0 to 1. When <span class="math inline">\(R^2\)</span> is close to 1, the model fits the dataset well. <span class="math inline">\(R^2\)</span> has a property that when adding more independent variables in the regression model, the <span class="math inline">\(R^2\)</span> will increase. There is another index called adjusted <span class="math inline">\(R^2\)</span>, which considers the number of variables in the models.</p>
<p>Our example is the Minneapolis ACS population dataset, and we want to explore the relationship between <code>EDUC</code> (Education level) and <code>AGE</code> (Age). Let’s draw a scatter plot to see their distribution.</p>
<div class="sourceCode" id="cb446"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb446-1"><a href="statistics-in-r.html#cb446-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(minneapolis_2017, <span class="fu">aes</span>(AGE, EDUC)) <span class="sc">+</span></span>
<span id="cb446-2"><a href="statistics-in-r.html#cb446-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="PA_5928_2021_spring_files/figure-html/unnamed-chunk-223-1.png" width="672" />
Because there are many overlapped points, we could add some noise to the positions of the points to help show all the points.</p>
<div class="sourceCode" id="cb447"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb447-1"><a href="statistics-in-r.html#cb447-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(minneapolis_2017, <span class="fu">aes</span>(AGE, EDUC)) <span class="sc">+</span></span>
<span id="cb447-2"><a href="statistics-in-r.html#cb447-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">size =</span> <span class="fl">0.5</span>) <span class="do">## add some noise to the positions of the points and set the size of the points to be 0.5</span></span></code></pre></div>
<p><img src="PA_5928_2021_spring_files/figure-html/unnamed-chunk-224-1.png" width="672" /></p>
<p>Based on the plot, it seems there is a positive relationship between these two variables. We add a linear line to fit them with <code>geom_smooth()</code>.</p>
<div class="sourceCode" id="cb448"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb448-1"><a href="statistics-in-r.html#cb448-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(minneapolis_2017, <span class="fu">aes</span>(AGE, EDUC)) <span class="sc">+</span></span>
<span id="cb448-2"><a href="statistics-in-r.html#cb448-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb448-3"><a href="statistics-in-r.html#cb448-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&#39;lm&#39;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="PA_5928_2021_spring_files/figure-html/unnamed-chunk-225-1.png" width="672" /></p>
<p>To quantify this linear relationship, We could use <code>lm()</code> function to fit this linear relationship and use <code>summary()</code> function to see the result. In the function, the formula indicates the model in assumption. Here, our model in assumption is,</p>
<p><span class="math display">\[EDUC = \beta_0 + \beta_1 \times AGE + \epsilon\]</span></p>
<p>When we code this model in R, we do</p>
<pre><code>EDUC ~ AGE</code></pre>
<p>We only need to write down the variable names of the dependent variable and independent variables, and use <code>~</code> to connect them. No need to write the intercept and error term.</p>
<p>We also need to indicate the name of the dataset in the function.</p>
<div class="sourceCode" id="cb451"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb451-1"><a href="statistics-in-r.html#cb451-1" aria-hidden="true" tabindex="-1"></a>lm_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(EDUC <span class="sc">~</span> AGE,      <span class="co"># formula</span></span>
<span id="cb451-2"><a href="statistics-in-r.html#cb451-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> minneapolis_2017) <span class="co"># dataset</span></span>
<span id="cb451-3"><a href="statistics-in-r.html#cb451-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_fit)             <span class="co"># check result</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = EDUC ~ AGE, data = minneapolis_2017)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.1979  -2.8243   0.3888   2.7364   5.1528 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 4.037407   0.114684   35.20   &lt;2e-16 ***
## AGE         0.078687   0.002741   28.71   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.102 on 2855 degrees of freedom
## Multiple R-squared:  0.224,  Adjusted R-squared:  0.2237 
## F-statistic: 824.1 on 1 and 2855 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The summarized result provides details about the model results, such as the coefficients and p-values, the model’s <span class="math inline">\(R^2\)</span>, <em>etc.</em></p>
<p>Based on the information, we could know that the estimated coefficient for the intercept is 4.04, its p-value is <span class="math inline">\(&lt; 2e-16\)</span> with a mark <span class="math inline">\(***\)</span>, showing it is significant at 99.9% level. The estimated coefficient for <code>AGE</code> is 0.08, its p-value is <span class="math inline">\(&lt;2e-16\)</span> with a mark <span class="math inline">\(***\)</span>, showing it is significant at 99.9% level.</p>
<p>We could also know the <span class="math inline">\(R^2\)</span> is 0.224, and adjusted <span class="math inline">\(R^2\)</span> is 0.2237.</p>
<p>We could use the codes below to check the <span class="math inline">\(R^2\)</span> of the model directly.</p>
<div class="sourceCode" id="cb453"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb453-1"><a href="statistics-in-r.html#cb453-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_fit)<span class="sc">$</span>r.squared   <span class="co"># value of R2</span></span></code></pre></div>
<pre><code>## [1] 0.2239978</code></pre>
<p>And get the values of the coefficients directly.</p>
<div class="sourceCode" id="cb455"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb455-1"><a href="statistics-in-r.html#cb455-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(lm_fit)        <span class="co"># only check the coefficient</span></span></code></pre></div>
<pre><code>## (Intercept)         AGE 
##  4.03740708  0.07868725</code></pre>
<p>The model can be improved. From the scatter plot between <code>EDUC</code> and <code>AGE</code>, many respondents get to their highest level of education before the age of 25. After 25, <code>AGE</code> has trivial influence on <code>EDUC</code>. We, then, are interested in the relationship before the age of 25.</p>
<div class="sourceCode" id="cb457"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb457-1"><a href="statistics-in-r.html#cb457-1" aria-hidden="true" tabindex="-1"></a>minneapolis_age <span class="ot">&lt;-</span> <span class="fu">filter</span>(minneapolis_2017, AGE <span class="sc">&lt;=</span> <span class="dv">25</span>)</span>
<span id="cb457-2"><a href="statistics-in-r.html#cb457-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb457-3"><a href="statistics-in-r.html#cb457-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(minneapolis_age, <span class="fu">aes</span>(AGE, EDUC)) <span class="sc">+</span></span>
<span id="cb457-4"><a href="statistics-in-r.html#cb457-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb457-5"><a href="statistics-in-r.html#cb457-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&#39;lm&#39;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="PA_5928_2021_spring_files/figure-html/unnamed-chunk-229-1.png" width="672" /></p>
<div class="sourceCode" id="cb459"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb459-1"><a href="statistics-in-r.html#cb459-1" aria-hidden="true" tabindex="-1"></a>lm_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(EDUC <span class="sc">~</span> AGE, </span>
<span id="cb459-2"><a href="statistics-in-r.html#cb459-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> minneapolis_age)</span>
<span id="cb459-3"><a href="statistics-in-r.html#cb459-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_fit) </span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = EDUC ~ AGE, data = minneapolis_age)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.3077 -1.0348 -0.0909  0.9091  3.9091 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.615627   0.087077  -18.55   &lt;2e-16 ***
## AGE          0.405604   0.005307   76.43   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.303 on 1006 degrees of freedom
## Multiple R-squared:  0.8531, Adjusted R-squared:  0.8529 
## F-statistic:  5841 on 1 and 1006 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The model provides better fitness to the dataset now.</p>
<p>Most of the time, we need to examine the relationship between the dependent variable and more than one independent variable. In this case, drawing a plot to check the relationship before the analysis is not a good idea. We just do the regression directly.</p>
<p>The example below examines the relationship between <code>EDUC</code> and <code>AGE</code>, <code>SEX</code>, and <code>RACE</code>. when there is more than one independent variables, we use <code>+</code> to connect them in the formula. <code>RACE</code> is a categorical variable, so we transform it to a factor.</p>
<div class="sourceCode" id="cb461"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb461-1"><a href="statistics-in-r.html#cb461-1" aria-hidden="true" tabindex="-1"></a>mlm_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(EDUC <span class="sc">~</span> AGE <span class="sc">+</span> SEX <span class="sc">+</span> <span class="fu">factor</span>(RACE),</span>
<span id="cb461-2"><a href="statistics-in-r.html#cb461-2" aria-hidden="true" tabindex="-1"></a>          minneapolis_2017)</span>
<span id="cb461-3"><a href="statistics-in-r.html#cb461-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlm_fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = EDUC ~ AGE + SEX + factor(RACE), data = minneapolis_2017)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -10.4126  -2.2219   0.4191   2.4941   6.5838 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    5.020836   0.208105  24.126   &lt;2e-16 ***
## AGE            0.070253   0.002684  26.170   &lt;2e-16 ***
## SEX           -0.044017   0.110679  -0.398    0.691    
## factor(RACE)2 -2.413424   0.160769 -15.012   &lt;2e-16 ***
## factor(RACE)3 -1.714259   0.159498 -10.748   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.957 on 2852 degrees of freedom
## Multiple R-squared:  0.2955, Adjusted R-squared:  0.2945 
## F-statistic: 299.1 on 4 and 2852 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb463"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb463-1"><a href="statistics-in-r.html#cb463-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlm_fit)<span class="sc">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.2955301</code></pre>
<p>Again, without careful research design, the relationships shown by the regression model are all correlations, not causalities.</p>
</div>
<div id="logistic-regression" class="section level2" number="8.5">
<h2><span class="header-section-number">8.5</span> Logistic regression</h2>
<p>The above two examples both use continuous variables as their dependent variables. How about using a binomial variable (0 or 1 as its value) a dependent variable? Then we need to do logistic regression. There are many functions to do this. When interpreting the coefficients of the logistic regression result, the coefficient stands for the change of the log odds of the dependent variable to 1.</p>
<p>Here, we introduce the <code>glm()</code> function. We need to indicate <code>family = binomial</code> in the function.</p>
<div class="sourceCode" id="cb465"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb465-1"><a href="statistics-in-r.html#cb465-1" aria-hidden="true" tabindex="-1"></a><span class="do">## create a variable to indicate the poverty status of the respondents</span></span>
<span id="cb465-2"><a href="statistics-in-r.html#cb465-2" aria-hidden="true" tabindex="-1"></a>minneapolis_poverty <span class="ot">&lt;-</span> minneapolis_2017 <span class="sc">%&gt;%</span> </span>
<span id="cb465-3"><a href="statistics-in-r.html#cb465-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(INCTOT)) <span class="sc">%&gt;%</span> </span>
<span id="cb465-4"><a href="statistics-in-r.html#cb465-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">poverty =</span> <span class="fu">ifelse</span>(INCTOT <span class="sc">&lt;=</span> <span class="dv">12228</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb465-5"><a href="statistics-in-r.html#cb465-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb465-6"><a href="statistics-in-r.html#cb465-6" aria-hidden="true" tabindex="-1"></a><span class="do">## logistic regression</span></span>
<span id="cb465-7"><a href="statistics-in-r.html#cb465-7" aria-hidden="true" tabindex="-1"></a>logit_reg <span class="ot">&lt;-</span> <span class="fu">glm</span>(poverty <span class="sc">~</span> AGE <span class="sc">+</span> EDUC <span class="sc">+</span> SEX <span class="sc">+</span> <span class="fu">factor</span>(RACE),</span>
<span id="cb465-8"><a href="statistics-in-r.html#cb465-8" aria-hidden="true" tabindex="-1"></a>                 minneapolis_poverty,</span>
<span id="cb465-9"><a href="statistics-in-r.html#cb465-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> binomial)</span>
<span id="cb465-10"><a href="statistics-in-r.html#cb465-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit_reg)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = poverty ~ AGE + EDUC + SEX + factor(RACE), family = binomial, 
##     data = minneapolis_poverty)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.3815  -0.7066  -0.5090   0.8830   2.8188  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)    3.018926   0.270700  11.152  &lt; 2e-16 ***
## AGE           -0.031852   0.002971 -10.720  &lt; 2e-16 ***
## EDUC          -0.367547   0.022532 -16.312  &lt; 2e-16 ***
## SEX            0.096235   0.101052   0.952    0.341    
## factor(RACE)2  0.646833   0.145549   4.444 8.83e-06 ***
## factor(RACE)3  0.168694   0.146323   1.153    0.249    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 2983.5  on 2402  degrees of freedom
## Residual deviance: 2391.9  on 2397  degrees of freedom
## AIC: 2403.9
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Most of the information is similar with regression ones except that the logistic regression does not have <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span>. It uses AIC (Akaike information criterion) in indicate the goodness of the model. If one model has smaller AIC, it is better.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-visualization-with-ggplot2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="exploratory-data-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
